name: .conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.4
  - pandas
  - scipy
  - jupyter
  - matplotlib
  - geopandas
  - ipympl
  - biosppy
  - pip
  - pip:
    - \ipyfilechooser
    - opencv-python
    - git+https://github.com/emotional-cities/pluma-analysis.git@46cffe14b514d64a83483dbd07c93872ddc9577e
    - pythermalcomfort
    - unidecode
